### PR TITLE
Update public events agenda

### PR DESCRIPTION
**Pull request by Ashwin-op**
Update for #8 

Have updated all events and added new upcoming events sorted based on start time. Let me know if any changes to the UI or the logic is required.

Screenshot:
Screenshot from 2020-07-20 20-20-27

### CODE REVIEW

**Comment by arpansac** [comment]
The code looks great! Just some minor tweaks and we'll be ready to merge!

-  http://localhost:4200/communities/gdg-new-delhi/events/developer-days-1-let-s-learn-angular
   - The timetable doesn't load, this was a bug even in the last timetable, I've changed it, let me know if you need my help in it
   - It shows the past session also in 'upcoming-sessions'

Screenshot 2020-07-21 at 7 07 50 PM


- **Upcoming events** tab should be conditionally visible basis the availability of the upcoming events, just adding image for reference, the url is: http://localhost:4200/communities/gdg-new-delhi/events/firebase-with-web
Screenshot 2020-07-21 at 7 11 34 PM

- **Upcoming events** Would be great if you can align all the external link icons at the bottom, and may be, also wrap around the complete card in an <a>. The link icon should remain though, because it tells the user that this will open in a new page. Also, do add status="primary" to nb-icon. It gives it color

Screenshot 2020-07-21 at 7 13 32 PM


- **Main Time Table**
  - Can we align all the links to the right, it'll make things standard
  - The sessions should be aligned as per starting time
  - Including the thumbnail of the speaker would be a good idea in the box
  - The text is overflowing in case of a lengthy title
  - Tags are overlapping the speaker's name. I think it's a good idea to move the speaker name to the next line
  - Track name should be in a larger font size with an icon
  - Probably we should show the count of tracks at the top

Screenshot 2020-07-21 at 7 18 17 PM

**Comment by Ashwin-op** [comment]
Sure, I'll do those changes, some clarifications

- _"Would be great if you can align all the external link icons at the bottom, and maybe, also wrap around the complete card in an . "_ --> I didn't quite understand this
- Aligning all the links under "All events" to the right might make the user scroll right if there is some other track slot with a long name. So, I'm confused about whether to make the change.
- _"Tags are overlapping the speaker's name. I think it's a good idea to move the speaker name to the next line
"_ --> Can you share a screenshot of this, I'm not able to reproduce this error.

I am working on the other changes :smile:

**Comment by arpansac** [comment]
Thanks for the new changes, I'll merge them super soon

**Comment by arpansac** [comment]
Closed by mistake

**Pull request merged**
