### PR TITLE
Sitemap Generator

### LINKED ISSUE #14: Sitemap
Integrate a sitemap generator, or just create a sitemap

### PR DESCRIPTION
**Pull request by Ashwin-op**
Generates the sitemap every week At 00:00 on Sunday. Closes #14

### CODE REVIEW

**Comment by arpansac** [comment]
Thanks a ton! We're releasing a host of new features/pages today, will take a look at it just after this :)

**Comment by arpansac** [comment]
Hey! Can you help me test this once more please? As in any set of steps?

**Comment by Ashwin-op** [comment]
If you want to test it offline, you can use [act](https://github.com/nektos/act).
`act -j sitemap` should do the job.


You can also test it by creating a private repo using this version and running GitHub Actions at a different time.


Let me know if something is not working as it should.

**Comment by arpansac** [comment]
Great, thanks, let me try it :)

**Comment by arpansac** [comment]
Got a little delayed, I've tested it. Do you think there's a way we could automate it using github actions on this repository itself?

**Comment by Ashwin-op** [comment]
Like without using a python file and generating sitemap completely using GitHub actions (or) do you mean something else?

**Comment by arpansac** [comment]
Yup, some github action which executes this python script and automatically
updates the sitemap file either in this or any other repository.

**Comment by Ashwin-op** [comment]
Sure, I'll look into it and let you know in around 2 days. I'll keep this PR as it is and start working on a new branch

**Comment by arpansac** [comment]
Closing this one as we have a new PR for the same by @Ashwin-op only :)

**Pull request closed without merging**
