### PR TITLE
Change "kommunity" with "community"

### PR DESCRIPTION
**Pull request by harsh26apr**
Change "kommunity" to "community"

### CODE REVIEW

**Comment by arpansac** [comment]
Will pull this in some time! There's a ton of changes + testing + data_migration required to be done for this on the server side...!

**Comment by arpansac** [comment]
Delaying this a little more, I'll need time for this.

**Comment by harsh26apr** [comment]
> Delaying this a little more, I'll need time for this.

No problem!

**Comment by harsh26apr** [comment]
@arpansac Gentle Reminder!

**Comment by arpansac** [comment]
Hi @harsh26apr 

Thanks! Actually this is on my list and I've started working on this. It's just very low on priority as of now, but don't worry, we'll reach there. Till then I strongly encourage you to take up another issue :)

**Comment by arpansac** [comment]
This has yet again moved lower on the list of priorities, everytime a new feature comes up, this gets backstaged, apologies @harsh26apr

**Pull request closed without merging**
