### PR TITLE
style: add tailwind class 2

### PR DESCRIPTION
**Pull request by ArshdeepGrover**
Tailwind class added and font size chnges as per documentation

### CODE REVIEW

**Comment by ArshdeepGrover** [comment]
image

image

image

image

image

**Review by arpansac — APPROVED** [review]

**Comment by ArshdeepGrover** [comment]
> Desktop View

image


image


image


image


image

**Comment by ArshdeepGrover** [comment]
> Mobile View

image

image

image


image

image

image

**Comment by arpansac** [comment]
> > Mobile View
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image

Check for gap on mobile (left has gap, right has none)

**Review by arpansac — APPROVED** [review]

**Pull request merged**
