### PR TITLE
Add contributors.md

### PR DESCRIPTION
**Pull request by muthuannamalai12**
I have added Contributors.md file in your project in the form of a table and displayed a link to it in README.md

### CODE REVIEW

**Comment by arpansac** [comment]
> I have added Contributors.md file in your project in the form of a table and displayed a link to it in README.md

This is super cool. Can you please also share some screenshots in the comments here? I will merge it within this week

**Comment by muthuannamalai12** [comment]
> > I have added Contributors.md file in your project in the form of a table and displayed a link to it in README.md
> 
> This is super cool. Can you please also share some screenshots in the comments here? I will merge it within this week

OK. I will add the screenshots in the comment

**Comment by muthuannamalai12** [comment]
Contributors

**Comment by arpansac** [comment]
> > > I have added Contributors.md file in your project in the form of a table and displayed a link to it in README.md
> > 
> > 
> > This is super cool. Can you please also share some screenshots in the comments here? I will merge it within this week
> 
> OK. I will add the screenshots in the comment

Thanks a ton :)

**Comment by arpansac** [comment]
> I have added Contributors.md file in your project in the form of a table and displayed a link to it in README.md

Was just about to merge, there's 1 question, right now that file is hard coded list of people in a table. How can we automate it to be picking up from github automatically. Or may be a script which updates it periodically

**Comment by muthuannamalai12** [comment]
> > I have added Contributors.md file in your project in the form of a table and displayed a link to it in README.md
> 
> Was just about to merge, there's 1 question, right now that file is hard coded list of people in a table. How can we automate it to be picking up from github automatically. Or may be a script which updates it periodically

All contributors bot can be used if the contributors keep increasing

All contributors bot

**Comment by arpansac** [comment]
> > > I have added Contributors.md file in your project in the form of a table and displayed a link to it in README.md
> > 
> > 
> > Was just about to merge, there's 1 question, right now that file is hard coded list of people in a table. How can we automate it to be picking up from github automatically. Or may be a script which updates it periodically
> 
> All contributors bot can be used if the contributors keep increasing
> 
> All contributors bot

Great! Will you be able to set it up?

**Comment by muthuannamalai12** [comment]
> > > > I have added Contributors.md file in your project in the form of a table and displayed a link to it in README.md
> > > 
> > > 
> > > Was just about to merge, there's 1 question, right now that file is hard coded list of people in a table. How can we automate it to be picking up from github automatically. Or may be a script which updates it periodically
> > 
> > 
> > All contributors bot can be used if the contributors keep increasing
> > All contributors bot
> 
> Great! Will you be able to set it up?

I will do it

**Comment by muthuannamalai12** [comment]
> > > > > I have added Contributors.md file in your project in the form of a table and displayed a link to it in README.md
> > > > 
> > > > 
> > > > Was just about to merge, there's 1 question, right now that file is hard coded list of people in a table. How can we automate it to be picking up from github automatically. Or may be a script which updates it periodically
> > > 
> > > 
> > > All contributors bot can be used if the contributors keep increasing
> > > All contributors bot
> > 
> > 
> > Great! Will you be able to set it up?
> 
> I will do it

@arpansac. Adding contributors using the contributor bot would be easily done by the owner of the repo because we have to go and add comments on the issue/pull request they made on your repo which I cannot access. You can do it by installing the all contributor bot and by specifying @all-contributors add @<username> for <contributions> tags like mentioned in the link mentioned here https://allcontributors.org/docs/en/emoji-key after that it would create a pull request and then you can merge it. 
Bot
The output looks like the photo mentioned below
Bot 1

**Comment by muthuannamalai12** [comment]
@arpansac .Now I have automated the contributors file by using this website https://contrib.rocks/preview. Kindly review it again

We just need to give our repository name in the website mentioned above and it would auto generate contributor images for us

**Comment by arpansac** [comment]
Super cool @muthuannamalai12 let me review and merge this either today/tomorrow, was engaged in some work...!

**Comment by muthuannamalai12** [comment]
> Super cool @muthuannamalai12 let me review and merge this either today/tomorrow, was engaged in some work...!

Ok. Thank you

**Comment by muthuannamalai12** [comment]
@arpansac Kindly add the level label as mentioned in my issue here also

**Pull request merged**
