### PR TITLE
Sharing handles added

### PR DESCRIPTION
**Pull request by aparth33**
Sharing handles added in form of js file. Will show icons at left side of every page in floating fashion.

### CODE REVIEW

**Comment by arpansac** [comment]
Have you tested the code?

**Comment by arpansac** [comment]
addthis.com looks very interesting, but I suppose we will need a custom component so that we can place it as per our convenience and probably change the design as well. Can you send in some screenshots and also confirm if your changes are working?

Plus I can see a lot of unnecessary indentation changes too, can you please remove them

**Comment by aparth33** [comment]
Yeah Its working fine !
Screenshot from 2020-07-16 16-36-53

**Comment by amanintech** [comment]
@arpansac I think they're much better ways then share this. Like using AMP share component

**Comment by arpansac** [comment]
Yup! We've decided to make our own components, this isn't fitting what we
want to do...!

**Comment by arpansac** [comment]
Closing this for now. Please create a new PR once you have built the component

**Pull request closed without merging**
